apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-billing-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-billing
  template:
    metadata:
      labels:
        app: hms-billing
    spec:
      containers:
        - name: hms-billing
          image: namankr301/hms_billing
          env:
            - name: MONGO_URI
              value: "mongodb://hms-billing-mongo-srv:27017/hms-billing"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: homestay
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: hms-billing-redis-srv
---
apiVersion: v1
kind: Service
metadata:
  name: hms-billing-srv
spec:
  selector:
    app: hms-billing
  ports:
    - name: hms-billing
      protocol: TCP
      port: 3000
      targetPort: 3000
